@startuml
actor Usuario
boundary Registro
control ApiREST
database BaseDatos
alt#Gold #LightBlue caso Ingreso Datos Cedula De Identidad (existo)
Usuario -> Registro: Ingresa datos
activate Registro

Registro --> ApiREST: Crear Ususuario\n url: "/api/Crear_usuario"\n methods: GET 
Activate ApiREST

ApiREST -> BaseDatos: Consulta: Buscar usuario por CI\n Table: User
Activate BaseDatos
BaseDatos --> ApiREST: Resultado: Buscar usuario por CI\n
deactivate BaseDatos
ApiREST --> Registro: Devuelve mensaje de no encontrado
Registro --> Usuario: Muestra el mensaje de no encontrado

else #Pink Usuario existente

ApiREST --> Registro: Devuelve los datos encontrado
deactivate ApiREST

Registro --> Usuario: Muestra el mensaje de Usuario ya existe
'destroy ApiREST

deactivate Registro
end
