@startuml
left to right direction
actor Administrador as g

package Administracion {
  usecase "Agendar Paciente" as UC1
  usecase "Registrar Paciente" as L1
  usecase "Editar Cita" as UC2
  usecase "Imprimir Boleta" as UC4

}
(UC1) .down.> (L1) : <<include>>
g --> UC1

g --> UC2


g --> UC4
@enduml
